[build]
command = "node -r ./crypto-polyfill.cjs ./node_modules/@react-router/dev/bin.js build"
publish = "build/client"

[dev]
command = "react-router dev"
targetPort = 5173

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
